# Generated by Django 2.1.4 on 2019-01-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('eval_set', models.CharField(max_length=20, null=True)),
                ('order_number', models.IntegerField(null=True)),
                ('order_dow', models.IntegerField(null=True)),
                ('order_hour_of_day', models.IntegerField(null=True)),
                ('days_since_prior_order', models.FloatField(max_length=20, null=True)),
                ('vip', models.BooleanField(null=True)),
            ],
        ),
    ]
