# Generated by Django 2.1.4 on 2019-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20190103_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='days_since_prior_order',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='eval_set',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
