# Generated by Django 2.1.4 on 2019-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20190103_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('department_id_vc', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('department_id_vc', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prior_reorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_set', models.CharField(max_length=200, null=True)),
                ('days_since_prior_order', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip_organic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=200, null=True)),
                ('product_name', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip_reorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_set', models.CharField(max_length=200, null=True)),
                ('days_since_prior_order', models.FloatField(max_length=200, null=True)),
            ],
        ),
    ]
