# Generated by Django 2.1.4 on 2019-01-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_day_night_prior_reorder_vip_organic_vip_reorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.FloatField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('aisle_id', models.FloatField(max_length=200, null=True)),
                ('aisle', models.CharField(max_length=200, null=True)),
                ('product_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
