# Generated by Django 2.1.4 on 2019-01-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_auto_20190104_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, null=True)),
                ('department_id', models.IntegerField(default=0, null=True)),
                ('aisle', models.CharField(max_length=100, null=True)),
                ('aisle_id', models.IntegerField(default=0, null=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('product_id', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
