# Generated by Django 2.1.4 on 2019-01-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20190104_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_final',
            new_name='Product',
        ),
    ]
