# Generated by Django 2.1.4 on 2019-01-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_product_product_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Night',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Prior_reorder',
        ),
        migrations.RemoveField(
            model_name='product_middle',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='product_small',
            name='aisle_id',
        ),
        migrations.DeleteModel(
            name='Vip_organic',
        ),
        migrations.DeleteModel(
            name='Vip_reorder',
        ),
        migrations.DeleteModel(
            name='Product_big',
        ),
        migrations.DeleteModel(
            name='Product_middle',
        ),
        migrations.DeleteModel(
            name='Product_small',
        ),
    ]
