# Generated by Django 2.1.4 on 2019-01-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_auto_20190106_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_middle',
            name='aisle_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
