# Generated by Django 2.1.4 on 2019-01-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_auto_20190106_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buys', models.IntegerField(default=999)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_small',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_small',
            name='product_id',
            field=models.FloatField(default=999999, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='buy',
            name='buyit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Product_small'),
        ),
    ]
