# Generated by Django 2.1.4 on 2019-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_auto_20190106_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_dow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sat', models.IntegerField(default=0, null=True)),
                ('Sun', models.IntegerField(default=0, null=True)),
                ('Mon', models.IntegerField(default=0, null=True)),
                ('Tues', models.IntegerField(default=0, null=True)),
                ('Wed', models.IntegerField(default=0, null=True)),
                ('Thrs', models.IntegerField(default=0, null=True)),
                ('Fri', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip_aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(max_length=200, null=True)),
                ('ratio', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vip_reorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('reordered', models.FloatField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='buyit',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='buy',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
