# Generated by Django 2.1.4 on 2019-01-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_auto_20190107_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_small',
            name='votes',
            field=models.IntegerField(default=999),
        ),
    ]
